# @Author Ananth Rao

version: '2'
services:
  web:
    restart: always
    build: ./app
    image: auditor
    ports:
      - "3000:3000"
    volumes: "./app"
    expose:
      - 3000
      - 443
    links:
      - redis
      - search
    env_file: .env

  search:
    restart: always
    build: ./services/search
    image: auditor-search
    ports:
      - "3001:3001"
    volumes: "./services/search"
    expose:
      - 3001
    links:
      - elasticsearch
      - redis
      - db
    env_file: .env

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    expose:
      - 9200

  db:
    image: mysql/mysql-server:latest
    # TODO: edit command to run seed file to prepopulate db
    expose: 3306

  redis:
    image: redis:latest
    expose:
      - "6379"
