const GET_RESULTS = 'GET_RESULTS'
const ADD_TO_SCHEDULE = 'ADD_TO_SCHEDULE'
const REMOVE_FROM_SCHEDULE = 'REMOVE_FROM_SCHEDULE'
const MAP_RECENTER = 'MAP_RECENTER'
const ADD_STOP = 'ADD_STOP'
const CHANGE_STOP = 'CHANGE_STOP'
const DELETE_STOP = 'DELETE_STOP'
const CHANGE_SUBJECT = 'CHANGE_SUBJECT'
const SEARCH = 'SEARCH'
const RECEIVE_RESULTS = 'RECEIVE_RESULTS'

export {GET_RESULTS, ADD_TO_SCHEDULE, REMOVE_FROM_SCHEDULE, MAP_RECENTER, ADD_STOP, CHANGE_STOP, DELETE_STOP, CHANGE_SUBJECT, SEARCH, RECEIVE_RESULTS}
